"""
PDF report generator using ReportLab.
"""
from pathlib import Path
from datetime import datetime
from typing import Dict
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY


class PDFReportGenerator:
    """Generates PDF vulnerability reports."""
    
    def __init__(self):
        """Initialize PDF generator."""
        self.styles = getSampleStyleSheet()
        self._setup_styles()
    
    def _setup_styles(self):
        """Setup custom paragraph styles."""
        self.styles.add(ParagraphStyle(
            name='Title',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a1a'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='Heading2',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#2c3e50'),
            spaceAfter=12
        ))
    
    def generate(self, results: Dict, output_dir: str = ".") -> str:
        """
        Generate PDF report from scan results.
        
        Args:
            results: Scan results dictionary
            output_dir: Output directory
        
        Returns:
            Path to generated report
        """
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        report_path = output_path / f"owaspguard_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
        doc = SimpleDocTemplate(str(report_path), pagesize=A4,
                                rightMargin=72, leftMargin=72,
                                topMargin=72, bottomMargin=18)
        
        story = []
        
        # Title
        story.append(Paragraph("OWASPGuard Security Report", self.styles['Title']))
        story.append(Spacer(1, 0.2*inch))
        
        # Summary
        story.append(Paragraph("Executive Summary", self.styles['Heading2']))
        self._add_summary_table(story, results)
        story.append(Spacer(1, 0.3*inch))
        
        # Findings by OWASP Category
        story.append(Paragraph("Findings by OWASP Top 10 Category", self.styles['Heading2']))
        self._add_owasp_breakdown(story, results)
        story.append(Spacer(1, 0.3*inch))
        
        # Detailed Findings
        story.append(Paragraph("Detailed Findings", self.styles['Heading2']))
        self._add_findings(story, results.get('findings', []))
        
        # Footer
        story.append(Spacer(1, 0.3*inch))
        footer = Paragraph(
            f"<i>Report generated by OWASPGuard on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</i>",
            ParagraphStyle(name='Footer', parent=self.styles['Normal'],
                          fontSize=8, textColor=colors.HexColor('#7f8c8d'),
                          alignment=TA_CENTER)
        )
        story.append(footer)
        
        doc.build(story)
        return str(report_path)
    
    def _add_summary_table(self, story, results: Dict):
        """Add summary table to story."""
        stats = results.get('stats', {})
        findings = results.get('findings', [])
        
        # Calculate severity breakdown
        severity_counts = {}
        scan_types = {}
        for finding in findings:
            severity = finding.get('severity', 'UNKNOWN')
            severity_counts[severity] = severity_counts.get(severity, 0) + 1
            scan_type = finding.get('scan_type', 'SAST')
            scan_types[scan_type] = scan_types.get(scan_type, 0) + 1
        
        data = [
            ['Files Scanned:', str(stats.get('files_scanned', 0))],
            ['Total Findings:', str(len(findings))],
            ['Scan Duration:', f"{stats.get('scan_duration', 0):.2f} seconds"],
            ['', ''],
            ['Severity Breakdown:', ''],
            ['  CRITICAL:', str(severity_counts.get('CRITICAL', 0))],
            ['  HIGH:', str(severity_counts.get('HIGH', 0))],
            ['  MEDIUM:', str(severity_counts.get('MEDIUM', 0))],
            ['  LOW:', str(severity_counts.get('LOW', 0))],
            ['  INFO:', str(severity_counts.get('INFO', 0))],
            ['', ''],
            ['Scan Types:', ''],
        ]
        
        for scan_type, count in scan_types.items():
            data.append([f'  {scan_type}:', str(count)])
        
        table = Table(data, colWidths=[2*inch, 4*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#ecf0f1')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2c3e50')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#bdc3c7'))
        ]))
        story.append(table)
    
    def _add_owasp_breakdown(self, story, results: Dict):
        """Add OWASP category breakdown."""
        categorized = results.get('categorized', {})
        
        data = [['OWASP Category', 'Findings Count']]
        for category, findings in sorted(categorized.items(), key=lambda x: len(x[1]), reverse=True):
            data.append([category, str(len(findings))])
        
        table = Table(data, colWidths=[4*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495e')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#bdc3c7'))
        ]))
        story.append(table)
    
    def _add_findings(self, story, findings: list):
        """Add detailed findings."""
        # Sort by severity score (highest first)
        sorted_findings = sorted(findings, key=lambda x: x.get('severity_score', 0), reverse=True)
        
        for idx, finding in enumerate(sorted_findings[:100], 1):  # Show top 100 findings
            if idx > 1:
                story.append(Spacer(1, 0.2*inch))
            
            # Finding header
            severity_score = finding.get('severity_score', 0)
            title = f"{idx}. {finding.get('description', 'Finding')} ({finding.get('severity', 'UNKNOWN')} - Score: {severity_score}/100)"
            story.append(Paragraph(title, self.styles['Heading3']))
            
            # Finding details - comprehensive
            details = [
                ['File:', finding.get('file_path', 'N/A')],
                ['Line:', str(finding.get('line_number', 'N/A'))],
                ['Severity:', f"{finding.get('severity', 'UNKNOWN')} (Score: {severity_score}/100)"],
                ['OWASP Category:', finding.get('owasp_category_full', finding.get('owasp_category', 'N/A'))],
                ['Scan Type:', finding.get('scan_type', 'SAST')],
                ['Rule ID:', finding.get('rule_id', 'N/A')],
            ]
            
            if finding.get('ml_confidence'):
                details.append(['ML Confidence:', f"{finding.get('ml_confidence', 0):.1%}"])
            
            if finding.get('confidence'):
                details.append(['Confidence:', finding.get('confidence', 'N/A')])
            
            if finding.get('exploitability'):
                details.append(['Exploitability:', finding.get('exploitability', 'N/A')])
            
            # SCA-specific details
            if finding.get('cve_id'):
                details.append(['CVE ID:', finding.get('cve_id', 'N/A')])
            if finding.get('package'):
                details.append(['Package:', finding.get('package', 'N/A')])
            if finding.get('version'):
                details.append(['Version:', finding.get('version', 'N/A')])
            
            # Secrets-specific details
            if finding.get('secret_type'):
                details.append(['Secret Type:', finding.get('secret_type', 'N/A')])
            
            if finding.get('line_content'):
                code_snippet = finding.get('line_content', '')
                # Truncate but show more context
                if len(code_snippet) > 200:
                    code_snippet = code_snippet[:200] + '...'
                details.append(['Code Snippet:', code_snippet])
            
            if finding.get('match'):
                details.append(['Match:', finding.get('match', 'N/A')[:100]])
            
            table = Table(details, colWidths=[1.5*inch, 4.5*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#ecf0f1')),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#2c3e50')),
                ('ALIGN', (0, 0), (0, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
            ]))
            story.append(table)
            
            # Comprehensive Remediation with detailed information
            story.append(Spacer(1, 0.15*inch))
            remediation_style = ParagraphStyle(
                name='Remediation',
                parent=self.styles['Normal'],
                fontSize=10,
                textColor=colors.HexColor('#27ae60'),
                leftIndent=20,
                spaceAfter=6
            )
            
            if finding.get('remediation'):
                remediation_text = finding.get('remediation', '')
                # Format remediation nicely
                story.append(Paragraph("<b>✅ Remediation Steps:</b>", self.styles['Normal']))
                story.append(Spacer(1, 0.05*inch))
                
                # Split by newlines or paragraphs
                remediation_parts = remediation_text.split('\n\n') if '\n\n' in remediation_text else [remediation_text]
                for part in remediation_parts:
                    if part.strip():
                        story.append(Paragraph(f"• {part.strip()}", remediation_style))
                        story.append(Spacer(1, 0.03*inch))
            elif finding.get('recommendation'):
                story.append(Paragraph("<b>✅ Recommendation:</b>", self.styles['Normal']))
                story.append(Spacer(1, 0.05*inch))
                story.append(Paragraph(f"• {finding.get('recommendation')}", remediation_style))
            
            # Additional context if available
            if finding.get('description') and len(finding.get('description', '')) > 100:
                story.append(Spacer(1, 0.1*inch))
                story.append(Paragraph("<b>📝 Additional Context:</b>", self.styles['Normal']))
                story.append(Spacer(1, 0.05*inch))
                context_style = ParagraphStyle(
                    name='Context',
                    parent=self.styles['Normal'],
                    fontSize=9,
                    textColor=colors.HexColor('#7f8c8d'),
                    leftIndent=20
                )
                story.append(Paragraph(finding.get('description', ''), context_style))
            
            if idx % 5 == 0:
                story.append(PageBreak())

